# Generated by Django 5.0.3 on 2024-04-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('release', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dupe_manufacturer', models.CharField(max_length=100, verbose_name='Dupe Manufacturer')),
                ('credits', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='Y', max_length=3, verbose_name='Credit Given')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chair')),
            ],
        ),
        migrations.CreateModel(
            name='Sightings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sighting Date')),
                ('location', models.CharField(choices=[('PER', 'Personal'), ('MUS', 'Museum'), ('SHO', 'Shop')], default='PER', max_length=3)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chair')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
