# Generated by Django 5.0.3 on 2024-04-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dupe',
            name='chair',
        ),
        migrations.AddField(
            model_name='chair',
            name='dupes',
            field=models.ManyToManyField(to='main_app.dupe'),
        ),
    ]
